config/routes.rb
LatinLinkManager::Application.routes.draw do
  resources :users
  resources :translators
  resources :clients
  match '/projects/closed/:id', to: 'projects#finished', via: 'put'
  match '/projects/open', to: 'projects#not_closed', via: 'get'
  match '/projects/closed', to: 'projects#closed', via: 'get'
  match '/projects/emailtranslator', to: 'projects#send_email', via: 'post'
  match '/projects/email/', to: 'projects#email', via: 'post'
  match '/orders/paid/:id', to: 'orders#paid', via: 'put'
  match '/orders/paid', to: 'orders#closed', via: 'get'
  match '/orders/unpaid', to: 'orders#open', via: 'get'
  resources :projects, only: [:index, :show, :new, :create, :destroy, :closed, :not_closed, :send_email]
  resources :assignments
  resources :assets
  resources :notes
  resources :orders
  resources :links
  resources :breakdowns
  resources :searches, only: [:new, :create, :show]
  resources :sessions, only: [:new, :create, :destroy]
  root to: 'static_pages#home'
  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'
  match '/newuser', to: 'users#new', via: 'get'
  match '/editaccount', to: 'users#edit', via: 'get'
  match '/allmanagers', to: 'users#index', via: 'get'
  match '/alltranslators', to: 'translators#index', via: 'get'
  match '/newtranslator', to: 'translators#new', via: 'get'
  match '/search/:table', to: 'searches#new', via: 'get'
  match '/orders/paid/:id', to: 'orders#paid', via: 'put'
  match '/orders/paid', to: 'orders#closed', via: 'get'
  match '/orders/unpaid', to: 'orders#open', via: 'get'
  match '/orders/', to: 'order#projects_from_client', via: 'get'
  match '/translatororder', to: 'order#translator_order', via: 'put'
  match '/clientorders', to: 'orders#clients', via: 'get'
  match '/translatororders', to: 'orders#translators', via: 'get'
  match '/clients/invoice/:id/:month', to: 'clients#invoice', via: 'get'
  match '/:month', to: 'static_pages#home', via: 'get'

end

app/models/asset.rb
class Asset < ActiveRecord::Base
	belongs_to :project
	has_attached_file :file, storage: :s3, default_style: :original, s3_permissions: :authenticated_read

	
	validates_attachment_file_name :file, :matches => [/xml\Z/, /XML\Z/, /zip\Z/, /ZIP\Z/]
	do_not_validate_attachment_file_type :file
end

app/models/assignment.rb
class Assignment < ActiveRecord::Base
	belongs_to :project
	has_one :translator
end

app/models/breakdown.rb
class Breakdown < ActiveRecord::Base
	belongs_to :project
end

app/models/client.rb
class Client < ActiveRecord::Base
	validates :name, presence: true
	validates :contact, presence: true

	has_many :projects, dependent: :destroy
	has_many :links
end

app/models/link.rb
class Link < ActiveRecord::Base
	belongs_to :project
	belongs_to :translator
end

app/models/note.rb
class Note < ActiveRecord::Base
	belongs_to :project
end

app/models/order.rb
class Order < ActiveRecord::Base
	default_scope -> { order('created_at DESC') }
	validates :LLID, presence: true
	validates :value, presence: true
	validates :category, presence: true
end

app/models/project.rb
class Project < ActiveRecord::Base
	# Projects belong to clients 
	belongs_to :client
	
	has_many :assignments, dependent: :destroy
	has_many :notes, dependent: :destroy
	has_many :assets, dependent: :destroy
	has_many :links, dependent: :destroy
	has_many :breakdowns, dependent: :destroy
	accepts_nested_attributes_for :assets
end

app/models/search.rb
class Search < ActiveRecord::Base
	validates :table, presence: true

	def translators
		@translators ||= find_translators
  	end

	private 
		def find_translators
			Translator.find(:all, :conditions => conditions)
		end

		def name_conditions
			["translators.name LIKE ?", "%#{name}"] unless name.blank?
		end


		def rate_conditions
			["translators.rate LIKE ?", "%#{rate}"] unless rate.blank?
		end

		def conditions
			[conditions_clauses.join(' AND '), *conditions_options]
		end

		def conditions_clauses
		  conditions_parts.map { |condition| condition.first }
		end

		def conditions_options
		  conditions_parts.map { |condition| condition[1..-1] }.flatten
		end

		def conditions_parts
		  private_methods(false).grep(/_conditions$/).map { |m| send(m) }.compact
		end
end

app/models/translator.rb
class Translator < ActiveRecord::Base
	before_save { self.email =  email.downcase }
	validates :name, presence: true
	validates :email, presence: true, uniqueness: { case_sensitive: false}
	validates :rate, presence: true

	has_many :links

	belongs_to :assignment

	def search
		self.find_translators
	end

	private

	def find_translators
		Translator.find(:all, :conditions => conditions)
	end

	def name_conditions
		["translators.name LIKE ?", "%#{name}"] unless name.blank?
	end

	def rate_conditions
		["translators.rate LIKE ?", "%#{rate}"] unless rate.blank?
	end
end

app/models/user.rb
class User < ActiveRecord::Base
	before_save { self.email =  email.downcase }
	before_create :create_remember_token
	validates :name, presence: true
	validates :email, presence: true, uniqueness: { case_sensitive: false}
	validates :signature, length: { minimum: 6 }
	has_secure_password
	validates :password, length: { minimum: 6 }
	validates :password_confirmation, presence: true

	def User.new_remember_token
		SecureRandom.urlsafe_base64
	end

	def User.digest(token)
		Digest::SHA1.hexdigest(token.to_s)
	end

	private

		def create_remember_token
			self.remember_token = User.digest(User.new_remember_token)
		end
end

app/helpers/assets_helper.rb
module AssetsHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

	def sign_in(user)
		remember_token = User.new_remember_token
		cookies.permanent[:remember_token] = remember_token
		user.update_attribute(:remember_token, User.digest(remember_token))
		self.current_user = user
	end

	def sign_out
		current_user.update_attribute(:remember_token, User.digest(User.new_remember_token))
		cookies.delete(:remember_token)
		self.current_user = nil
	end

	def signed_in?
		!current_user.nil?
	end

	def current_user=(user)
		@current_user = user
	end

	def current_user
		remember_token = User.digest(cookies[:remember_token])
		@current_user ||= User.find_by(remember_token: remember_token)
	end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<div class="col-xs-12 col-sm-12 col-md-8 col-lg-6 col-md-offset-2 col-lg-offset-3">
	<nav class="navbar navbar-default" role="navigation">
		<div class="container-fluid">
				<div class="navbar-header">
					<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
						<span class="sr-only">Toggle navigation</span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
					</button>
					<a class="navbar-brand" href="<%= root_url %>"><%= image_tag("logo.png") %></a>
				</div>

				<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
					<ul class="nav navbar-nav navbar-right">
						<% if signed_in? %>
						<li class="dropdown">
							<a class="dropdown-toggle" data-toggle="dropdown">Projects<span class="caret"></span>
							<ul class="dropdown-menu">
								<li><%= link_to "All Projects", projects_path %></li>
								<li><%= link_to "New Project", new_project_path %></li>
								<li><%= link_to "All Open Projects", projects_open_path %></li>
								<li><%= link_to "All Closed Projects", projects_closed_path %></li>
							</ul>
						</li>

						<li class="dropdown">
							<a  class="dropdown-toggle" data-toggle="dropdown">Translators<span class="caret"></span>
							<ul class="dropdown-menu">
								<li><%= link_to "All Translators", alltranslators_path %></li>
								<li><%= link_to "New Translator", newtranslator_path %></li>
							</ul>
						</li>

						<li class="dropdown">
							<a  class="dropdown-toggle" data-toggle="dropdown">Purchase Orders<span class="caret"></span>
							<ul class="dropdown-menu">
								<li><%= link_to "All Orders", orders_path %></li>
								<li><%= link_to "New Order", new_order_path %></li>
								<li><%= link_to "Clients", clientorders_path %></li>
								<li><%= link_to "Translators", translatororders_path %></li>
								<li><%= link_to "All Open", orders_unpaid_path %></li>
								<li><%= link_to "All Closed", orders_paid_path %></li>
							</ul>
						</li>

						<li class="dropdown">
							<a class="dropdown-toggle" data-toggle="dropdown">Clients<span class="caret"></span>
							<ul class="dropdown-menu">
								<li><%= link_to "All Clients", clients_path %></li>
								<li><%= link_to "New Client", new_client_path %></li>
							</ul>
						</li>

						<li class="dropdown">
							<a class="dropdown-toggle" data-toggle="dropdown">Managers<span class="caret"></span>
							<ul class="dropdown-menu">
								<li><%= link_to "All Managers", allmanagers_path %></li>
								<li><%= link_to "New Manager", newuser_path %></li>
							</ul>
						</li>

				        <li class="dropdown">
							<a class="dropdown-toggle" data-toggle="dropdown"><%= current_user.name %><span class="caret"></span>
							<ul class="dropdown-menu">
								<li><%= link_to "Edit account", editaccount_path %></li>
								<li class="divider"></li>
								<li><%= link_to "Sign out", signout_path, :method => :delete %></li>
							</ul>
						</li>

						<% else %>
							<li><%= link_to "Sign in", signin_path %></li>
						<% end %>
					</ul>
				</div>
			</div>
	</nav>
</div>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
  <meta name="viewport" content="width=device-width, initial scale=1.0">
</head>
<body>
	<%= render 'layouts/header' %>
  	<div class="col-xs-12 col-sm-12 col-md-8 col-lg-6 col-md-offset-3 cold-lg-offset-3 white">
  		<% flash.each do |key, value| %>
          	<div class="alert alert-<%= key %>"><%= value %></div>
        	<% end %>
  		<%= yield %>
  	</div>
	<%= render 'layouts/footer' %>
</body>
</html>

app/views/layouts/project_invoice.html.erb
<div id="header">
	<%= wicked_pdf_image_tag 'invoice_logo.png' %>
	<div class="address">
		Language Partners Ltd Trading as Latin Link
		91 Cotham Brow
		Bristol, BS6 6AW
		Company: 8113770
		VAT: GB150345246
	</div>
	to
	<div class="address">
		Client Address
	</div>
</div>

<div id="content">
	<div id="thanks">
		Many thanks for your recent business with Latin Link. Below is a breakdown of your invoice.
	</div>
	<table>
		<tr><td>Project ID</td><td>Deadline</td><td>Purchase Order</td><td>Cost</td></tr>
		<% @projects.each do |p| %>
			<% @orders.each do |o| %>
				<tr><td><%= "#{@client.name} #{@project.count}" %></td><td><%= "#{@project.deadline} #{@project.time}" %></td><td><%= @order.LLID %></td><td><%= @order.value %></td></tr>
			<% end %>
		<% end %>
	</table>
</div>
<div id="payment">
	Payments to be made by way of bank transfer:
	Language Partners Ltd
	Bank: Santander
	BIX: ABBYGB2LXXX
	IBAN: GB76ABBY09012830125046
	Sort code: 09-01-28
	Account number: 30125046
</div>
<div id="footer">
	<%= wicked_pdf_image_tag 'invoice_footer.png' %>
</div>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
	<div id="error_explanation">
		<ul>
			<% object.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
			<% end %>
		</ul>
	</div>
<% end %>